- build.rs
- src/error.rs
- src/lib.rs
- src/mutex.rs
Bring formatting into line with Rustfmt defaults
> Run cargo +nightly fmt over the repo

- src/include/esp-idf/bindings.h
necessary for https://github.com/esp-rs/esp-idf-svc/pull/14
> feat: add sntp include

- Cargo.toml
- build/build.rs
- build/common.rs
> Force ESP_ERR_* constants to be i32

- .github/workflows/publish.yml
As promised, a fix when #50 inevitably wasn't quite right :)
> Publish is a manual action, not a github event

- .github/workflows/publish.yml
Should be the last thing now, sorry for the noise!
> docs: redirect to correct folder name

- Cargo.toml
- build/build.rs
With the ability to opt back into the pio build driver.
> Default to native

- src/include/esp-idf/bindings.h
See https://github.com/espressif/esp-idf/tree/v4.3/components/fatfs/diskio .
> Add diskio headers from FATFS

- README.md
I think the badges make more sense up there.
>  Add badge to docs and hoist badges up

- src/include/esp-idf/bindings.h
> esp_int_wdt.h is a private include in esp-idf v5

- README.md
Hi, 
improve reading view in readme.
> send to next line for better reading experiance

- build/native/cargo_driver.rs
Fixes something missed in https://github.com/esp-rs/esp-idf-sys/commit/8a0e9280322071c337300de19efdf2807f7877e2
> apply patches on master and v5 branch

- README.md
> Clarify how bindings_header works

- build/common.rs
https://github.com/esp-rs/esp-idf-sys/actions/runs/3356732458/jobs/5562011749#step:7:250
> fix the CI with the new nightly clippy lints

- src/include/esp-idf/bindings.h
> Add Wi-Fi Easy Connect (DPP) bindings

- src/include/esp-idf/bindings.h
This is built on top of the task snapshot PR just so I can work with it easily. If these are very rarely used and hurt more than help, I can accept not merging this PR and I can probably go with an additional custom component header file.
> Export the HiMem APIs

- src/include/esp-idf/bindings.h
> Add BLE mesh bindings

- build/native/cargo_driver.rs
- build/native/cargo_driver/chip.rs
- src/include/esp-idf/bindings.h
Adds minimal support for the ESP32-P4.
> Add support for the esp32p4

- src/include/esp-idf/bindings.h
https://github.com/esp-rs/esp-idf-hal/issues/445  https://github.com/esp-rs/esp-idf-hal/pull/454 Related. Needed for the device iteration.
> Expose onewire device

- CHANGELOG.md
- src/app_desc.rs
Fixes #369.
see definition https://docs.espressif.com/projects/esp-idf/en/v5.4/esp32/api-reference/system/misc_system_api.html#_CPPv4N14esp_app_desc_t7reserv3E
> fix: esp_app_desc_t.reserv3 should be [0;3]

- .github/workflows/ci.yml
We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:
Bump xtensa-toolchain to v1.6
CI
> Bump xtensa-toolchain action
