esp-rs/esp-idf-sys

Cargo.toml
README.md
build.rs
build_native.rs
build_pio.rs
resources/cmake_project/CMakeLists.txt
resources/cmake_project/main.c

This is very work-in-progress work to compile the `esp-idf` using `cmake`.
Currently, it compiles (tested for esp32 on windows) but doesn't run when it has been flashed.
Please give feedback and/or tell me if you find something wrong.

Experimental esp-idf native cmake build

---

Cargo.toml
build.rs
build_native.rs
build_pio.rs
patches/master_missing_xtensa_atomics_fix.diff
resources/cmake_project/CMakeLists.txt
src/include/esp-idf/bindings.h
src/lib.rs

@N3xed:
Following set of native build fixes:
- Introduction of a new `rustc` cfg: ESP-IDF version. Derived by grepping the generated `bindings.rs` file for three constants (coming from `esp_version.h`: `ESP_IDF_VERSION_MAJOR`, `ESP_IDF_VERSION_MINOR` and `ESP_IDF_VERSION_PATCH`. 
- Why? Because it works regardless of the concrete build type: be it `pio` or `native`. As to why we are not basing the version on Git tags, that might be difficult as there is e.g. no proper git tag for ESP-IDF master. Als `git describe` returns nothing for `master`. Using the above integers help us e.g. "prepare" the codebase for a release to be branched off from ESP-IDF master, as these are correctly set there (to `4.4.0`)
- Bugfix (in `resources/cmake_project/CMakeLists.txt`) as to how the `SDKCONFIG` and …

Various fixes for the native build

---

src/include/esp-idf/bindings.h

esp32s3 does not have DAC peripheral.

Exclude DAC bindings for esp32s3

---

src/lib.rs

An official rwlock impl has been implemented in esp-idf (4.4 backport
imminent), hence for versions >4.3 we no longer need to link the patched
versions.
The current pthread rwlock implementation does not support attributes, is this a problem for Rust? I did a quick grep of the standard library and didn't spot any usage...
Closes #33

feature: gate mutex rwlock patches for v4.4+

---

README.md
build/common.rs
build/native.rs
build/pio.rs

This mostly implements the plan outlined [here](https://github.com/esp-rs/esp-idf-sys/issues/10#issuecomment-963380205).
Native and pio build now match with the sdkconfig configuration. Though I've implemented in addition to specifying the profile in the file name (like pio required before), that one can now also specify only the mcu or both. Also, the `.<profile>` requirement for pio has been lifted.
Selecting the sdkconfig now has the following precendence:
1. `<path>.<profile>.<chip>`
2. `<path>.<chip>`
3. `<path>.<profile>`
4. `<path>`
For the native build, the optimization configurations now don't conflict anymore. They are set using a generated `sdkconfig.defaults` file from the cargo [`opt-level`](https://doc.rust-lang.org/cargo/reference/profiles.html#opt-level) and …

Unify sdkconfig configuration options

---

.github/workflows/publish.yml
Cargo.toml

A stop gap until we figure out what to do with regards to docs.rs. The `documentation` key in `Cargo.toml` means crates.io docs button will point to our gh pages link, instead of docs.rs. This has almost all the same features as using docs.rs, however we won't have past versions documentation available once a new version is published.
Currently I've set it to only deploy with releases. 
sidenote: I'll be very shocked if this works first time so expect a follow up PR :D

docs: Add doc build to CI for GH pages

---

src/include/esp-idf/bindings.h

gives access to esp_crt_bundle_{set,attach,detach} which is unfortunately not transitively included by `esp-tls.h`

import esp_crt_bundle.h if using mbedtls

---

build/native.rs

Together with the [add cmake for aarch64 linux PR](https://github.com/ivmarkov/embuild/pull/41) it should be able to build [std-demo](https://github.com/ivmarkov/rust-esp32-std-demo) on RPi (aarch64 linux).
Closes #14

build: remove ulp_gcc_toolchain for aarch64 linux

---

build/common.rs
src/include/esp-idf/bindings.h

In order to implement wifi-provisioning (https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/provisioning/wifi_provisioning.html) the first step is to generate the bindings
That is done here

Add bindings for wifi-provisioning

---

src/patches.rs
src/patches/lstat.rs

All filesystems on esp-idf do not support symlinks, there for lstat on espidf platform is the same as stat.
This will be implemented in esp-idf eventually, but for now we can patch it in here.
Partially fixes https://github.com/esp-rs/rust/issues/100.

Patch in `lstat`

---

build/common.rs
src/include/esp-idf/bindings.h

The main PR is in `esp-idf-svc` - this just adds header to the bindings so that they get generated 
related: https://github.com/esp-rs/esp-idf-sys/issues/70

add esp-now support: add bindings for esp_now

---

build/common.rs
src/include/esp-idf/bindings.h

To enable use of the ESP-IDF "console" component (https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/console.html) in a Rust application, such as a Rust port of the console example apps (https://github.com/espressif/esp-idf/tree/4dc74c9/examples/system/console), this branch enables the component and generates bindings for its esp_console.h, linenoise.h, and argtable3.h header files.

enable console component and generate bindings for its header files

---

.github/configs/sdkconfig.defaults
.github/workflows/ci.yml

~~Requires https://github.com/esp-rs/xtensa-toolchain/pull/6 to be merged first.~~ This is now merged.
I was able to delete `.github/configs/sdkconfig.defaults` since it's no longer required. If you like this, I will also do this for the other workflows in this repo as well as for the other esp-rs repos.

Use a build matrix to also build for xtensa architectures

---

.github/workflows/ci.yml
.github/workflows/publish.yml
Cargo.toml
README.md
build/native.rs

- Upgrade `embuild` to 0.30
- Upgrade bindgen to 0.60
- Add automatic release tagging on publish
Nothing groundbreaking, just upgrading embuild (and with it bindgen) for which I've just published a new major version. I've also added to embuild, and now here, automatic tagging to the publish workflow. It tags the current revision with a `v<crate version>` tag. Additionally, I've changed the tag format (it was only `<version>` before) to `v<version>` to make it more consistent with our other repositories.
Fixes #53

Upgrade embuild, bindgen, add automatic tagging

---

src/include/esp-idf/bindings.h

Not absolutely essential, but the functions in these headers make setting up BLE applications a lot easier!

Include headers for NimBLE GAP & GATT services

---

src/include/esp-idf/bindings.h

Usb host component is missing in esp-idf-sys bindings. By using this variable `CONFIG_USB_OTG_SUPPORTED` we can depend on header only being picked up on supported boards. It is currently enabled for [ESP32 S3](https://github.com/espressif/esp-idf/blob/2b1bee166d4d5b55549063e93a4c1be86e9c9da3/components/soc/esp32s3/include/soc/soc_caps.h#L40)   and for [ESP32 S2](https://github.com/espressif/esp-idf/blob/2b1bee166d4d5b55549063e93a4c1be86e9c9da3/components/soc/esp32s2/include/soc/soc_caps.h#L49).

Add usb host to bindings

---

src/include/esp-idf/bindings.h

Added Https in bindings.h. Is needed for #https://github.com/esp-rs/esp-idf-svc/pull/123.

Add https server bindings.

---

src/include/esp-idf/bindings.h

For being able to implement [ESP-WIFI-MESH](https://www.espressif.com/en/products/sdks/esp-wifi-mesh/overview) functionality into the `esp-idf-svc` crate, let's add related bindings here.

Add ESP-WIFI-MESH bindings

---

README.md

I found it difficult to follow the abstract wording here and first tried to set debug-profile-specific settings by adding a sdkconfig.defaults.debug file rather than sdkconfig.debug. Added an example that hopefully clarifies for others.

Add concrete example of multiple sdkconfig files.

---

src/app_desc.rs

Accordingly to linker scripts(`components/esp_system/ld/esp32s3/sections.ld.in` and others) and previously add patches application description is stored in `rodata_desc` section. Changing this brought app descriptor back to the beginning of binary file.

Fix wrong section name in esp_app_desc macro

---

resources/cmake_project/CMakeLists.txt

related to espressif/esp-idf#10082 which is caused by this being absent

Initialize target specific information in CMake

---

Cargo.toml
build/build.rs
build/common.rs
build/native/cargo_driver.rs
patches/esp_app_format_weak_v5.0.diff
src/alloc.rs
src/app_desc.rs
src/error.rs
src/lib.rs
src/panic.rs
src/patches.rs
src/patches/lstat.rs
src/patches/pthread_rwlock.rs

- reintroduce `esp_app_desc` patch for v5.0
- move to `bindgen` 0.63, `core::ffi` `size_t` = `usize`
- Requires esp-rs/embuild#66

Move to `bindgen` 0.63, `core::ffi` `size_t` = `usize`

---

src/alloc.rs

A compilation error will occur if no_std and riscv32imc-esp-espidf target.
( https://github.com/taks/esp32-nimble/actions/runs/3664876683/jobs/6195572914#step:6:238 )

Adjust for esp-idf-sys size_t u32->usize

---

src/error.rs

I'm sure this can optimize the stack for a lot of methods returning `Result<(), EspError>` out there.
I also added an infallible method using eager const evaluation. There are a lot `EspError::from(ESP_ERR_*).unwrap()` in `esp_idf_hal` and `esp_idf_svc` that could be replaced with `EspError::from_infallible::<ESP_ERR_*>()`.

Apply Niche optimization to `EspError`, add infallible helper function

---

.github/workflows/ci.yml

- Starting in `1.66.0.0` script installer and version `0.2.4` of `espup`, `libncurses5` is no longer required as we use the [latest llvm release](https://github.com/espressif/llvm-project/releases/tag/esp-15.0.0-20221201)
- Update `xtensa-toolchain` action release. This release has an ongoing issue, see https://github.com/esp-rs/xtensa-toolchain/issues/15.
- We will be publishing a new release for the action shortly.

Remove libncurses5 installation

---

src/include/esp-idf/bindings.h

With this `include` added, bindings to the `esp_wifi_sta_wpa2_*` functions will be generated, which enable the usage of WPA2 Enterprise authentication.

Enable WPA2 bindings

---

src/include/esp-idf/bindings.h

Make additional ESP-IDF functionality available: the IDF libraries for Bluetooth profiles Advanced Audio Distribution Profile (A2DP) and Audio / Video Remote Control.

Add Bluedroid A2DP and AVRC profile implementations

---

build/build.rs

Fixes https://github.com/esp-rs/esp-idf-sys/issues/185
Unfortunately, this is a breaking change because it changes some of the FreeRTOS functions to take and return `*c_void` instead of `*tskTaskControlBlock`. Possible some other things, too, but this is the only change I encountered. Since this PR is a correctness fix, I think this breakage is justified.

Define `ESP_PLATFORM`

---

src/include/esp-idf/bindings.h

In ESP-IDF 5.0, the I2S driver underwent a major rewrite. The new driver requires including a new set of header files. The old driver is still available (and is still included here and has bindings provided) but is deprecated and slated for removal.
This is required for the [I2S driver being written for esp-idf-hal](https://github.com/esp-rs/esp-idf-hal/issues/205).

Include the I2S 5.x driver headers.

---

src/include/esp-idf/bindings.h

Various socket related bindings are only exposed when the `esp_http_client` component is enabled. This PR adds the relevant header to the `lwip` component to remedy that.

Expose socket bindings when HTTP client is disbaled

---

build/native/cargo_driver.rs

The check for `>= 4.4` was incorrect and considered 5.0 to be before 4.4 (because the minor version was checked even for major versions greater than 4).
This resulted in us installing an older cmake version for esp-idf 5.0. This in turn resulted in builds on macos-arm64 failing (likely due to some separate bug) with the following error:
Using esp-idf v5.0.1 at '/Users/jenkins/jenkins_root/workspace/p/_target/xtensa-esp32s3-espidf/debug/build/esp-idf-sys-875fc790415fd0c8/out/espressif/esp-idf-3e3d654f8a323aea/v5.0.1'
ERROR: tool cmake does not have versions compatible with platform macos-arm64
Error: Could not install esp-idf
Caused by:
command '"/Users/jenkins/jenkins_root/workspace/p/_target/xtensa-esp32s3-espidf/debug/build/esp-idf-sys-875fc790415fd0c8/out/espressif/python_env/idf5.0_py3 …

build: avoid using custom cmake on esp-idf 5.x (where x < 4)

---

src/include/esp-idf/bindings.h

When using the LwIP sockets API directly, one is likely to want to access lwip/netdb.h, as demonstrated by the examples in https://docs.espressif.com/projects/esp-idf/en/v5.0.1/esp32/api-guides/lwip.html#examples, so this branch includes that header file in bindings.h if ESP_IDF_COMP_LWIP_ENABLED.
As well, to use the tcp_transport component, it's necessary to include its header files, so this branch includes those files as well in bindings.h if ESP_IDF_COMP_TCP_TRANSPORT_ENABLED.

Generate bindings for lwip/netdb.h, esp_transport*.h

---

src/include/esp-idf/bindings.h

This change includes the I2S headers for ESP-IDF v4.4, allowing the Rust I2S driver being considered in this pull request to build on that version of ESP-IDF.
https://github.com/esp-rs/esp-idf-hal/pull/232

Allow I2S builds on v4.4.

---

src/include/esp-idf/bindings.h

@ivmarkov mentioned they do not remember why the `esp_crc.h` header was removed, but I suspect it may have to do with it now being part of the [esp_rom component](https://github.com/espressif/esp-idf/tree/master/components/esp_rom). Some ROM functions are only available on certain chips, but the extracted ones like `esp_rom_crc.h` **"are expected to exist across all chips. If some of them are missed in the new chips, we will implement them again in `esp_rom/patches`."**
More headers from `esp_rom` could be included, but I'll take it one step at a time and start with CRC because I need it. I wrote working sample code that uses this [at my repository](https://github.com/jordanhalase/test-esp-idf-sys-crc/blob/master/src/main.rs).
```rust
use esp_idf_sys::*;
const CRC_INITIAL: u32 = …
```

Add esp_rom_crc.h to bindings

---

src/patches.rs

judging from the code and from some issue I've read in the past the statement that the link_patches() call is a no_op with idf_version >=4.4 is false.

remove misleading untrue comment

---

BUILD_OPTIONS.md

My `sdkconfig.defaults` file is always ignored. And it takes so much time before I figure out why. I never have `CARGO_TARGET_DIR` unset, because I don't want to fill up my source code folders with build artifacts. This `embuild` caveat is poorly documented. It would be great if the `esp-idf-sys` documentation would mention it.
I would add a link to a reference on why this is needed if I had one. But I can't remember where I learned about this workaround. I learned about it a long time ago but then I forget about it every time I pick up esp programming.

Add note about CARGO_TARGET_DIR requiring CARGO_WORKSPACE_DIR

---

BUILD_OPTIONS.md
Cargo.toml
src/lib.rs
src/start.rs

This buffers stdin and stdout (which, itself, is not a big deal), but also allows for reading from stdin over UART0 when debugging firmware. This uses a feature, enabled by default, called `uart0_driver_init` that calls a bit of initialization
code just before the user's Rust `main()` is invoked to perform its job.
Updated documentation to reflect this change.
Fixes https://github.com/esp-rs/esp-idf-hal/issues/200

Initialize UART0 with the driver.

---

build/build.rs
src/include/esp-idf/bindings.h
src/lib.rs

This provides bindings for the PCNT peripheral using the ESP-IDF v5+ definitions in conjunction with the ESP-IDF v4 definitions. It removes a case where bindgen can't cope with a typename that exists in two namespaces (`enum pcnt_unit_t` in v4, `struct pcnt_unit_t` in v5) by manually handling this special case.
This is a different take on the problem than https://github.com/esp-rs/esp-idf-sys/pull/156 and should allow esp-idf-hal to continue to run peacefully (and punts the porting problem there into the future).

Provide PCNT v5 bindings.

---

src/include/esp-idf/bindings.h

This wasn't bound before and as far as I can see, it doesn't need any specific config to be set in order to be available.

Generate bindings for esp_freertos_hooks.h

---

build/build.rs
src/include/esp-idf/bindings.h
src/lib.rs
src/pcnt.rs

Re-do of https://github.com/esp-rs/esp-idf-sys/pull/229
This provides bindings for the PCNT peripheral using the ESP-IDF v5+ definitions in conjunction with the ESP-IDF v4 definitions. It removes a case where bindgen can't cope with a typename that exists in two namespaces (enum pcnt_unit_t in v4, struct pcnt_unit_t in v5) by manually handling this special case.
This is a different take on the problem than https://github.com/esp-rs/esp-idf-sys/pull/156 and should allow esp-idf-hal to continue to run peacefully (and punts the porting problem there into the future).
Tested this time against actual targets that *have* PCNT peripherals.

PCNT v5 bindings take 2

---

src/include/esp-idf/bindings.h

Including the new ADC api headers.  This makes ADC calibration available for esp32c6 wgen using esp-idf >= 5.1.1 and the new api available for esp-idf >= 5.0.0.

include new ADC api

---

build/config.rs

I got an error when i tried to build without the "native" feature active:
```
error[E0026]: struct `BuildConfig` does not have a field named `native`
--> esp-idf-sys/build/config.rs:129:21
|
129 |                     native: _,
|                     ^^^^^^ struct `BuildConfig` does not have this field
For more information about this error, try `rustc --explain E0026`.
error: could not compile `esp-idf-sys` (build script) due to previous error
```
For completeness sake, I thought this might have been interesting for you upstream.

build/config.rs: non-native build fix

---

src/include/esp-idf/bindings.h

The following error occurs when compiling for esp32c6 with NimBLE enabled.
```
Caused by:
clang diagnosed error: /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-idf-sys-0.33.3/src/include/esp-idf/bindings.h:401:10: fatal error: 'esp_nimble_hci.h' file not found
```
The file 'esp_nimble_hci.h' seems to be used only for esp32, esp32s3, and esp32c3.
refer to:
- https://github.com/espressif/esp-idf/blob/8fc8f3f47997aadba21facabc66004c1d22de181/components/bt/host/nimble/Kconfig.in#L667
- https://github.com/espressif/esp-idf/blob/8fc8f3f47997aadba21facabc66004c1d22de181/components/bt/CMakeLists.txt#L664

Fix compile error for esp32c6 with NimBLE.

---

src/include/esp-idf/bindings.h

https://docs.espressif.com/projects/esp-idf/en/v5.1.1/esp32/migration-guides/release-5.x/5.1/networking.html

Export `esp_netif_sntp` APIs from esp-idf 5.1

---

src/app_desc.rs

Zero out time and date fields of `esp_app_desc_t` when `esp_idf_app_compile_time_date` is not set

Make builds of `esp_app_desc` reproducible

---

Cargo.toml
build/config.rs

cargo metadata unfortunately by default runs in some mode where it always run for "all targets". In our case it will download all windows specific crates on all platform targets, even if they are never used. This cost a lot of space for nothing. 
I first bumped up the version of the cargo_metadata crate and now added a flag that should prevent this behavior. I tested it inside a new environment with this patch and it seams to work.  
This PR fix: #260

stop cargo metadata from downloading rust crates not needed for the host platform

---

src/include/esp-idf/bindings.h

Prerequisite for getting the internal temperature sensor in various ESP32 chips working.
Also see this issue over in esp-idf-hal: https://github.com/esp-rs/esp-idf-hal/issues/333

Add temperature sensor header for ESP32C3

---

src/include/esp-idf/bindings.h

This introduces the LCD bindings for the ESP32-S3, as suggested in #216.

Export LCD bindings for ESP32-S3

---

src/error.rs

`core::ffi::CStr` is stable since 1.64.

Simplify `Display` for `EspError`.

---

src/error.rs

Hello,
This pull request explicitly implements Debug for EspError, so the human readable error string is shown instead of the error number inside the struct
This doesn't seem to have a negative impact, instead, in my application it seems to **reduce** code size
with this pr:
`App/part. size:    846,240/8,323,072 bytes, 10.17%`
with the original code:
`App/part. size:    848,720/8,323,072 bytes, 10.20%`
So 3 flash pages are freed with this modification
this pr:
```
called `Result::unwrap()` on an `Err` value: ESP_ERR_ESPNOW_NOT_FOUND (error code 12393)
```
original code:
```
called `Result::unwrap()` on an `Err` value: EspError(12393)
```

Custom debug for EspError

---

src/include/esp-idf/bindings.h

- new implementation of `i2c` does not expose commands interface, so the `transaction` function in the `esp-idf-hal` couldn't be used anymore. 
1. Now is the question to keep the legacy implementations for a `I2CDriver` implementation with the transaction interface. This will lead to `#include hal/i2c_types.h` because the legacy header exposes types from the hal. The new `i2c` implementation could be used for an extra `I2CBusDriver`.
2. The other solution would be to request a public interface to a transactional operation in the new `i2c` implementation in `esp-idf`.

Add new i2c includes for idf 5.2

---

.github/workflows/ci.yml

As discussed on Matrix, this PR is parallelizing the build of `sys` against the various ESP IDF versions. For now, I've excluded the PIO build from CI so that we get comparable figures.
(One thing svc has which sys doesn't is a lot of examples, so svc will spend much more time in linking, but we'll see).

CI: Parallelize the build

---

Cargo.toml

The changelog of bindgen added a lot between 0.63 and 0.69 though it still seams to work without any problems. They introduces some new features that may be interesting in the future - like creating bindgens for C functions that are inlined in the api and thus currently not producing any bindgen output etc. 
This change is also needed when https://github.com/esp-rs/embuild/pull/85 lands so we have version parity between both

⬆️ update bindgen to latest version

---

src/include/esp-idf/bindings.h

This PR allow to use `usb_serial_jtag_driver_install` function and to set USB Serial to blocking mode on esp32-c3, which could be useful for reading from stdin

Adding usb-serial

---

src/include/esp-idf/bindings.h

The driver should also work for the esp32c6 and upcoming p4

expose sdio_slave.h for all targets that support it and add onewire_bus.h

---

src/include/esp-idf/bindings.h

I am using dns_gethostbyname_addrtype to do parallel resolution of IPv4 and IPv6 addresses with async callbacks in my project.
Adding this header file would help me greatly.

Add raw bindings to the internal DNS resolver API

---

build/common.rs
build/native/cargo_driver.rs

This is mostly rebasing #353 so that it is mergable after the latest changes in `master`.

Nix - support - rebase https://github.com/esp-rs/esp-idf-sys/pull/353

---

CHANGELOG.md
src/include/esp-idf/bindings.h

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:
See https://github.com/esp-rs/esp-idf-svc/issues/537 for more details. The goal is to be able to access the underlying `netif` struct from an `esp_netif_t`. 
Works. The necessary function is exposed properly:
```rust
use esp_idf_svc::sys::esp_netif_get_netif_impl
```

Expose bindings

---

README.md

ESP IDF can’t be compiled on filesystems without support for symbolic links because it creates a virtual python venv during build which requires symlinks (at least on Linux).
Closes #366

Add note about FAT incompatibility to README
